apiVersion: v1
kind: Service
metadata:
  name: cpucontrol6
spec:
  type: NodePort
  selector: 
    app: cpu-control6
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-control6
  labels:
    app: cpu-control6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-control6
  template:
    metadata:
      labels:
        app: cpu-control6
    spec:
      containers:
        - name: cpu-control
          image: notexactlyawe/cpu-control:latest
          ports:
            - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busy-worker6
  labels:
    app: busy-worker6
spec:
  selector:
    matchLabels:
      app: busy-worker6
  template:
    metadata:
      labels:
        app: busy-worker6
    spec:
      containers:
        - name: busy-worker
          image: notexactlyawe/busy-worker:latest
          env:
            - name: SERVICE_NAME
              value: "CPUCONTROL6"
          resources:
            requests:
              cpu: "1"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: busy-autoscaler6
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: busy-worker6
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 30
