apiVersion: v1
kind: Service
metadata:
    name: cpucontrol
spec:
    type: NodePort
    selector: 
        app: cpu-control
    ports:
        - protocol: TCP
          port: 80
          targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: cpu-control
    labels:
        app: cpu-control
spec:
    replicas: 1
    selector:
        matchLabels:
            app: cpu-control
    template:
        metadata:
            labels:
                app: cpu-control
        spec:
            containers:
                - name: cpu-control
                  image: notexactlyawe/cpu-control:latest
                  ports:
                      - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: busy-worker
    labels:
        app: busy-worker
spec:
    selector:
        matchLabels:
            app: busy-worker
    template:
        metadata:
            labels:
                app: busy-worker
        spec:
            containers:
                - name: busy-worker
                  image: notexactlyawe/busy-worker:latest
                  resources:
                      requests:
                          cpu: "300m"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: busy-autoscaler
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: busy-worker
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 50
