apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
controllerManager:
  extraArgs:
    horizontal-pod-autoscaler-downscale-stabilization: "10s"
apiServer:
  extraArgs:
    feature-gates: SCTPSupport=true
networking:
  podSubnet: "10.244.0.0/16"
